const ACTION_PREPEND = "salto-game/battle";
export const CREATE_CARD = `${ACTION_PREPEND}/CREATE_CARD`;
export const ADD_CARD_TO_DECK = `${ACTION_PREPEND}/ADD_CARD_TO_DECK`;
export const ADD_CARD_TO_BATTLE_DECK = `${ACTION_PREPEND}/ADD_CARD_TO_BATTLE_DECK`;

export const REMOVE_CARD_FROM_BATTLE_DECK = `${ACTION_PREPEND}/REMOVE_CARD_FROM_BATTLE_DECK`;
export const REMOVE_CARD_FROM_DECK = `${ACTION_PREPEND}/REMOVE_CARD_FROM_DECK`;

export const DECREMENT_ACTIONS = `${ACTION_PREPEND}/DECREMENT_ACTIONS`;
export const ENABLE_TARGET_SELECTION = `${ACTION_PREPEND}/ENABLE_TARGET_SELECTION`;
export const DISABLE_TARGET_SELECTION = `${ACTION_PREPEND}/DISABLE_TARGET_SELECTION`;
export const CREATE_MONSTER = `${ACTION_PREPEND}/CREATE_MONSTER`;
export const ADD_MONSTER = `${ACTION_PREPEND}/ADD_MONSTER`;
export const ATTACK_MONSTER = `${ACTION_PREPEND}/ATTACK_MONSTER`;
export const ATTACK_TARGETED_MONSTER = `${ACTION_PREPEND}/ATTACK_TARGETED_MONSTER`;

export const SET_BATTLE_DECK = `${ACTION_PREPEND}/SET_BATTLE_DECK`;

export const ADD_TO_BATTLE_HP = `${ACTION_PREPEND}/ADD_TO_BATTLE_HP`;
export const SET_BATTLE_CURRENT_AP = `${ACTION_PREPEND}/SET_BATTLE_CURRENT_AP`;
export const SET_BATTLE_MAX_AP = `${ACTION_PREPEND}/SET_BATTLE_MAX_AP`;
export const SET_QUEUED_ACTIONS = `${ACTION_PREPEND}/SET_QUEUED_ACTIONS`;
export const SET_SELECTED_TARGET = `${ACTION_PREPEND}/SET_SELECTED_TARGET`;
export const SET_MONSTER_MOVES = `${ACTION_PREPEND}/SET_MONSTER_MOVES`;
export const RESET_ALL_MONSTER_MOVES = `${ACTION_PREPEND}/RESET_ALL_MONSTER_MOVES`;
export const ADD_BATTLE_TURN = `${ACTION_PREPEND}/ADD_BATTLE_TURN`;
