//monsters
export const ADD_MONSTER = "ADD_MONSTER";
export const ATTACK_MONSTER = "ATTACK_MONSTER";

//cards
export const CREATE_CARD = "CREATE_CARD";

//player
export const ADD_CARD_TO_DECK = "ADD_CARD_TO_DECK";
export const REMOVE_CARD_FROM_DECK = "REMOVE_CARD_FROM_DECK";

export const ADD_CARD_TO_HAND = "ADD_CAR_TO_HAND";
export const REMOVE_CARD_FROM_HAND = "REMOVE_CARD_FROM_HAND";

export const ADD_CARD_TO_DISCARD = "ADD_CARD_TO_DISCARD";
export const REMOVE_CARD_FROM_DISCARD = "REMOVE_CARD_FROM_DISCARD";